version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/app.Dockerfile
    volumes:
      - ..:/workspaces/lab:cached
      - nuget-packages:/root/.nuget/packages
    working_dir: /workspaces/lab
    command: sleep infinity
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    depends_on:
      - db
    mem_limit: 2g
    cpus: 1.5

  db:
    build:
      context: ..
      dockerfile: .devcontainer/db.Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
      - ../scripts:/scripts:ro
    mem_limit: 2g
    cpus: 1.5

volumes:
  nuget-packages:
  sql-data:
